name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    name: Python ${{ matrix.python-version }}, django ${{ matrix.django-version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version: [32]

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Ubuntu Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gettext
      - name: Install Dependencies
        run: |
          make deps
          pip install -e .
          pip install coveralls

      - name: Run Tests
        env:
          TOXENV: django${{ matrix.django-version }}
        run: tox
